group: bluezone
dist: trusty
sudo: false
language: node_js
node_js:
- 6.9.0
addons:
  sonarqube: true
before_install:
- echo "@console:registry=https://dev-console-npm.stage1.ng.bluemix.net/" > ~/.npmrc
- echo -e "//dev-console-npm.stage1.ng.bluemix.net/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
- npm i -g npm@3
- npm install
script:
- npm test
- sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.github.endpoint=$GH_API_URL
  -D sonar.github.oauth=$SONAR_GITHUB_TOKEN
after_success:
- npm run build
- npm run semantic-release
cache:
  directories:
  - node_modules
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
#
# Add secure environment variables using the following command:
#    travis encrypt YOUR_ENV_VAR=[value] --add env.global
#
# Required env vars:
# - GH_TOKEN
# - NPM_TOKEN
# - SONAR_TOKEN
# - SONAR_GITHUB_TOKEN
#
# See https://ibm.biz/graphql-data-source-travis for details.
#
env:
  global:
  - SONAR_HOST_URL=http://ux-dev-sonar.rtp.raleigh.ibm.com:9000/
  - GH_API_URL=https://github.ibm.com/api/v3
#
# Optional: send Slack notifications.
# See https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
#
# notifications:
#   slack:
#     rooms: "<account>:<token>#room"
#     on_success: change
#     on_failure: change
#
