group: bluezone
dist: trusty
sudo: false
language: node_js
node_js:
- 6.9.0
addons:
  sonarqube: true
before_install:
- echo "@console:registry=https://dev-console-npm.stage1.ng.bluemix.net/" > ~/.npmrc
- echo -e "//dev-console-npm.stage1.ng.bluemix.net/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
- npm i -g npm@3
- npm install
script:
- npm test
- sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.github.endpoint=$GH_API_URL
  -D sonar.github.oauth=$SONAR_GITHUB_TOKEN
after_success:
- npm run build
- npm run semantic-release
cache:
  directories:
  - node_modules
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
env:
  global:
  - SONAR_HOST_URL=http://ux-dev-sonar.rtp.raleigh.ibm.com:9000/
  - GH_API_URL=https://github.ibm.com/api/v3
  - secure: BDYyYIwPsSHnEU/pnX33ZzwtU4hujmvwc15ilM/JPHIB5fKQWolokNiBGXG5nB/LYRxgB6GUm56A1Q9PNmmDUNeD1vLcgWOaNpyob/LBEi4ibVpGfM/JKV7XgXNSapRJvULI7nrps+HRzfxKl6BCIA3fxTT0E0iIETx7hCPwgZzkNpOtR1bISCR9v8xmCullBIeZoBzSICZFzRqVq9PS5aK06Uz/ssxnltfpnN2AHZBQexCnln3Iy4lmHY+A/JTnd8MVmLO0FhBZK2U6jvTAWwZJzhJ/aj8mEkvMo0vPd7op12xIM9iTbbsD7YUSISpcP3TtBYLazwONfyqjPy7upsR0wKq7YMuWB/+9phuGowXGR+03z/335zusuLljhzZEKdWC/LhP1k490mdIbSLFZKxG7Qjv4JR5mzNZnaQpqosun7Nug05kgD0aDtWzeZ00hSOy4ntYnWw+irBy1D3k3r1iQzglnRLEEIavdQSKD0hy6kwb+DxRCepYoVSLFeVq0aekFVmepTmIiV7CQAj8IVNr7+2O3EG9gG0ZCC9mEhEGpU5X09s2v8Lq0dSf+hBjSOwugK1MwOovPNQPjbcpUzJp3mmBggMmiMWULMRj8AUJVVD+DgFIJfeUs+fW2ba/UcBPBFN1GQTargrXNLyHY3cUuakHRBOPuLhWbrvGf70=
  - secure: nRbuefZawBecAti+g8aZ91CxORaboSTt4h4cH9Eg+NJ/eAiy8DM14eqed57y8/ztSTSiibQXMk8AyEFlJB4woDE2agGxO+Wy4KTbSMgwgqU/KyqNUNWYjKkyS+w0NvATwyx/8Xtok0Z5OpsY3ovzYi4tpg5ygY5YP584G3IKyw1QHqJDpocrrIVQWBlcJa1jVa9c+3QZW0TKp1gb8Bz8PbJaEc9J1iWAteA+oSwYIMqT2W9jLR57+OlaapmeURwjeO31KMzN9M6X5xkdKwuWBpUHSHJRXIbHVs8ypE8p8rRNHbL0RJJ0BOiEmMAsvDE/PxsABexdSJNYqg0VqhiRjKlOW8ynnJ9ZVD2CYt/yKxdwLvjZzzLNE/FX5cYpgThPbYLQgDocCErNp5M0PhYMXcICLOldmYiIvXLjNAz4+y5mevcmU3y5fDcHgncwW+fZLiIP5iaCoeI0b14NqE/EbR+lvIdIrdSketgBg2ZqDmz6CEnkdyCx185gp8Ye1PhMadCVJks/MCku2bm8C5V0FaxlH900vNFQyS017Lu0dAtaHxBGoWhEjMw96FtRQuf44u3SbtQBLISLSywp+t5tjQkxRtNWBw5bh9Dl25vi+Kksm7vEQ4QeA8BiZHIHiL2VQrGY0xAL0JaYIj/BS45QkerToTeAKpQFjCnWZVmM8mU=
  - secure: hKO+iK6rfxLYM754whKwTtp/wysygDJ07jear3bmEG3yVzGStm0jnOuWP0ArPfrsMSDWcmY8b9iGr5nuEP/PpRR0e7nFMY+ACLrK96q6ooE0oceAqIqPkWuznLLHKe+U4Vmybn2Cs/OUVMeQWHIM20O/OKPyJ9CSs64933HV5iq/rKBmrfZSyTdjM06A3bXcxkWaJAskbk8mK+tI7one0IDU5/RkLQXcpORV37pfdEpE/U8hJk/Lh9MxNYD/39S7Z2wnhqJAk34yqm9QUmgTLMOag/bTK1Tdx3iObyxWsf7Dm/P1oC7Niqobc64MpZByq+THXwlG0GGsKLazhQ0VoBM/CGQjt5J5x2k267c0B6vWnR7XDeW/ua19JNUwtqjCVXuZHhUjmCd/L9h2mR2drfk5cBwtIMQMmW0ZnXiOUW9bkCwhjTqVU1o9FiIhuas+icyy62o+U9sXyiOqOPisaJwIdHBivrZkDK60OcHDxvdsySb4SMItiIeZoNONoJgEicZ2QpclwsNk6SizYUS66k2fIy5BRtlkNOePQypqM38PVfhV8KjzbdV1QgJ1eoOkXG1bo7rX9YBigM9P1zHpoypfM1VDMSuoWXk5TYhtSddUtT6v9NMkUtLrPhFv2jYLHIPACHgD/CT9P+pDyIU6L0Eik9hN1MNWj2+KawcXZI8=
  - secure: KPumMoLYWl/AL7YhStp/OduGOnQjJQfmAtS3Vt2pPcL4wDCeym/A0muFioAdR1q996i2tQ3caVm5NRT9uty8lA+VP1RSlSJE06a59XLaH+eOoCcwkvmZ3Dqzr9bTGFAdVS6v21UO5VeASlSg0wDMzhivfvXKy34ih1X782UQv7Gv8YAmAUT9JC3BA66KT6yNcKh7vLtQcbuCsC4I8ykw1Y8gu1kvcPtAuUh9aQ9dAy3KD5wsSuRyIqIhTeYw4i9sipAN53TeEWaazZfZ+hPUS17EYEgGXCv0sJ5LVxpSnV7aWELI9WY7AkoweajMC3ODSkBKUhaxiyuFE1809nTRU8g0xzJcfv5V31dzWXvbJZlbWUvkfz/PYKeftY2mfQk30ozSlWOHC/NVSHQqzIByxVotISbeX1MqELaB0riAa7/46e8C7++fD3a0wI/MOD0NPibeFV7fHvvFlOOrcQDny13vSW2HgBd2CieTbLlzjv4aiqKePVFGNzEqdSFNVP5cdEBgiD3P3oqJT9nEOZsXaykZLvPB2RkW4A3Z8oRhEltziDUIsI67hD0XAF/sG2PWCBZcDUvwo8RJdvTkYeZowf2yzePRMFQ+WQXD5A1UK36FnVkdjDKzPCsMt90VTbYN3g6/+NG8jzDORKsBnxYGSqbLrhITob8jRjHJop7BVxw=
notifications:
  slack:
    rooms:
      secure: upzWEKLOztL4nZmFNUZ+c1x/5fkYy09qxejgiFA1/7vXo5uzKjOEMH5mYT81C2Ao2AKh5wZy0koBU0EuBd27RZuWRcGvejkAzzyOiZqjOMQoc7tiQJLL88kLRthqZiLNJZADMWDouqHfOIMW0CqUzyltK/37Cc5UN7OFHO75snHbm6GtoPQ8moaR73+QtOG9w1uGs8k+vK7dWTXIvUeko5ywxZq7Fc+9nWGmZ3hiBLl4SO9JrunjOU8iKHuLKfhhZ1pshQKj+XhpUfb6sw2pEcNd/SNX54bmkhWPu85D3JIqp0BMN/LakLqSMAbNV0yg9qCKSNpIrTBTkVYh4d+RhDh3iojbYrO6AECjj3ojXAwD/TyHjrgLUTvPmf+1+Z4CcE7uZyBbSfktMV1zwVNh21qekDXR/NFcb8h2jCKxKJ2hKnkC4g41vrulMgZb3RjbkQHrBU578r2Yf7/mpdjYB+vE/D657kW2ud5JX9wg4JALUJySlQvR6PBc+E4fAjPNjabjABbpMrND7FjZEKA0Uu9yz9GzA6rQCt3+mg+s/nLD6JzjnhwPDtJT3bMnfML/8+nFJZ7pmfK27Kt3HGUJVAvMehAvwYWK2FHPkjhwgzlp9jcjf9n7Pais+Zt+6RZK9nDO0fkThkZPvMzppYqmH1E2SO3lY3OMmBEVOrPHKF8=
    on_success: change
    on_failure: change
